# Question 1


In [5]:
import numpy as np
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

#For question 1(a)
print("addtion is")
print(A+B)

#For question 1(b)
print("multipication is")
print(A*B)

#For question 1(c)
print("simplification is")
print(3*A-2*B)


addtion is
[[ 3  1]
 [-3  7]]
multipication is
[[ 2 -2]
 [ 0 12]]
simplification
[[ 4 -7]
 [ 6  1]]


# Question 2

In [20]:
#For question 2(a)
det = round(np.linalg.det(A),2)
print(f"The determinant of matrix A is: {det}")

print()
#For question 2(b)
if(not det==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of matrix A is: 6.0

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


# Question 3


In [19]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


# Question 4

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the features (x1, x2, x3) and prices
X = np.array([[4, 1.5, 100], [6, 2.0, 150]])  # Feature matrix
y = np.array([20, 30])  # Prices

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X, y)

# Define the features of car 3
x3 = np.array([[8, 3.0, 200]])

# Predict the price of car 3
predicted_price = model.predict(x3)

print(f"The predicted price of car 3 is: {predicted_price[0]:.2f}")





The predicted price of car 3 is: 40.00
